repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: "https://github.com/psf/black"
    rev: 21.11b1
    hooks:
      - id: black
  - repo: "https://github.com/PyCQA/isort"
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: "https://github.com/PyCQA/flake8"
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=100]
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-comprehensions
          - flake8-logging-format
          - flake8-pytest-style
          - flake8-simplify
  - repo: "https://github.com/PyCQA/pylint"
    rev: v2.12.1
    hooks:
      - id: pylint
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v0.910-1
    hooks:
      - id: mypy
